### ISSUE TITLE
pede o .env mesmo não usando

### ISSUE THREAD

**Issue by wgnann** [Transparencia-Brasil/achados-epedidos-ocr-extractor#1]
criar um .env com qualquer conteúdo parece resolver

**Comment by studiocuboweb** [comment]
@wgnann o problema de criar um .env com qualquer conteúdo é que ele ficará armazenado no github e isso vai contra a proposta dele: utilizar um .env para cada ambiente e deixá-lo no gitignore.

No deploy do github daria para criar alguma rotina que copia o .env.example (que está no github) para .env?

Ou eu posso mover as variáveis de ambiente do .env para o docker-compose.yml

**Comment by wgnann** [comment]
dá para fazer o composer fazer essa cópia

**Comment by studiocuboweb** [comment]
Isso resolve?

https://github.com/Transparencia-Brasil/achados-epedidos-ocr-extractor/commit/2d0769c857368760980c992e034abe1c5d860658

**Comment by wgnann** [comment]
Parece que sim.
