### ISSUE TITLE
não usa SSL para se conectar

### ISSUE THREAD

**Issue by wgnann** [Transparencia-Brasil/achados-epedidos-ocr-extractor#2]
precisa arrumar o conector do mysql para usar SSL e, eventualmente, receber o path do CA

**Comment by studiocuboweb** [comment]
@wgnann está feito conforme pull request.
https://github.com/Transparencia-Brasil/achados-epedidos-ocr-extractor/pull/5

adicionei uma nova variável de ambiente MYSQL_ATTR_SSL_CA e caso ela esteja setada e preenchida o sistema usa uma nova conexão do mysql com suporte para o ssl. Caso ela não esteja setada e ou setada e vazia o sistema usa a conexão tradicional do mysql sem o ssl.

Testei aqui local e funcionou. testa ai e se tiver tudo certo pode fechar o ticket.

**Comment by wgnann** [comment]
Acessou o banco.
