### ISSUE TITLE
FILES_PATH está estranho

### ISSUE THREAD

**Issue by wgnann** [Transparencia-Brasil/achados-epedidos-ocr-extractor#3]
aparentemente ele exige que o diretório seja terminado por `/` em alguns lugares. exemplo: `/mnt/achados/` em vez de `/mnt/achados`

**Comment by studiocuboweb** [comment]
@wgnann 

Eu verifiquei aqui o meu .env e o arquivo indexador.php e o FILES_PATH já está terminando com a /

Meu .env está dessa forma:

````
API_URL=http://achadosepedidos.org.br/api
FILES_PATH=/mnt/achados-e-pedidos-bucket/
BUCKET_PATH=gs://achados-e-pedidos-bucket/
````

Dei uma olhada na API_URL e não vejo problemas de terminar sem o /

Se o Files_path já está com / 

Onde pode estar o problema? Aliás, aparece algum erro no console?

**Comment by studiocuboweb** [comment]
@wgnann coloquei o / na aplicação e agora as variáveis de ambiente relacionadas a caminhos dos arquivos / logs deve ser configuradas sem o / no final. como exemplo:
`````
API_URL=http://achadosepedidos.org.br/api
FILES_PATH=/mnt/achados-e-pedidos-bucket
BUCKET_PATH=gs://achados-e-pedidos-bucket
`````
Pode fechar?
