### ISSUE TITLE
bloquear o acesso ao indexador.php

### ISSUE THREAD

**Issue by wgnann** [Transparencia-Brasil/achados-epedidos-ocr-extractor#4]
é possível acessá-lo via navegador dado que ele vai para o diretório de deploy via git

**Comment by studiocuboweb** [comment]
@wgnann fiz esse commit aqui no master:
https://github.com/Transparencia-Brasil/achados-epedidos-ocr-extractor/commit/eb3ec3a7bc049dfc3dec5c0f1eb69d939ff736e4

creio que um .htacess com Deny from all bloqueia qualquer acesso à pasta.

Eu não consigo testar isso aqui. Favor testar. se estiver tudo certo, só fechar o issue

**Comment by wgnann** [comment]
Forbidden. Funcionou.
