### ISSUE TITLE
Caminho ao drive azure não está montado e precisa de permissão de escrita no Google Cloud

### ISSUE THREAD

**Issue by studiocuboweb** [Transparencia-Brasil/achados-epedidos-ocr-extractor#8]
@wgnann 

Já trocamos o acesso ao Google Bucket para o Azure bucket (o acesso é através do drive montado dentro do servidor do google).

problemas:

1. A pasta /mnt/drive-azure não está mais montada. Creio que um restart na máquina desfez o mount. Um ls -la na pasta não está retornando a listagem de pastas e arquivos
![Screen Shot 2021-07-19 at 10 42 23](https://user-images.githubusercontent.com/32527574/126169816-676716ea-0451-4d31-966d-a4a12ecb9ca0.png)

2. Será necessário permissão de escrita no bucket da azure montado para armazenamento de arquivos de log.

**Comment by wgnann** [comment]
Teoricamente, a configuração de montagem está no `/etc/fstab`, então o reboot deveria resolver. Pode acontecer de faltar alguma coisa na hora do reboot, aí é preciso rodar um `sudo mount -a`.

Eu deixei o seu usuário com permissão de escrita. É ele quem costuma rodar as coisas?
```
$ ls -lash | tail -1
 512 -rwxr-xr-x 1 paulo_campos root  190 Jul  8 11:34 RltIndexador-08-07-2021-11-34.csv
```

**Comment by wgnann** [comment]
Se não der certo, aí só resta o análogo ao `chmod 777`, que eu não gostaria de usar.

**Comment by studiocuboweb** [comment]
@wgnann o usuario que acessa é o paulo_campos.

Consegui rodar lá. deu certo e inclusive deu para extrair texto de arquivo e salvar no elastic search.

Tudo funcionando perfeito.

Vou fechar o issue.

Obrigado Will
